### ISSUE TITLE
List already exists exception when executing ApplyProvisioningTemplate

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#151]
When executing `ApplyProvisioningTemplate`; `ObjectListInstance.cs` throws a "List already exists" exception, whereas the function should check for duplicates. It appears there is already a document library with the same title, whereas the function now only checks for duplicates in the list name. By the way, the exception is currently not very useful as it is not stated which list is the cause.
I am using assembly version 1.7.1015.1 of OfficeDevPnP.Core.

Exception details:
```
Microsoft.SharePoint.Client.ServerException was unhandled
  _HResult=-2146233088
  _message=Er bestaat al een lijst, enquête, discussiebord of documentbibliotheek met de opgegeven titel in deze website. Kies een andere titel.
  HResult=-2146233088
  IsTransient=false
  Message=Er bestaat al een lijst, enquête, discussiebord of documentbibliotheek met de opgegeven titel in deze website. Kies een andere titel.
  Source=Microsoft.SharePoint.Client.Runtime
  ServerErrorCode=-2130575342
  ServerErrorTraceCorrelationId=d7f73d9d-2d5b-004a-345e-8d3712ae2e14
  ServerErrorTypeName=Microsoft.SharePoint.SPException
  ServerStackTrace=   at Microsoft.SharePoint.SPGlobal.HandleComException(COMException comEx)
   at Microsoft.SharePoint.Library.SPRequest.CreateList(String bstrWebUrl, String bstrTitle, String bstrDescription, String bstrListUrl, String bstrFeatureId, Int32 lTemplateID, String bstrDocTemplateType, ListQuickLaunchOptions qlOpt, Boolean bProvisionViewsAndForms, ISPEnableModuleCallback pListInstanceModuleCallback, String bstrListInstanceSolutionInfo, String bstrListInstanceFeaturePath, String bstrListInstanceFeatureId, String bstrCustomSchemaXml, ISPEnableModuleCallback pListTemplateModuleCallback, String bstrListTemplateSolutionInfo)
   at Microsoft.SharePoint.SPListCollection.CreateList(String strTitle, String strDescription, String strListUrl, String strFeatureId, Int32 templateID, String strDocTemplateType, String strDataSource, String customSchemaXml, SPFeatureDefinition listInstanceFeatureDefintion, QuickLaunchOptions qlOpt, CreateFlags flags)
   at Microsoft.SharePoint.SPListCollection.Add(String title, String description, String url, String featureId, Int32 templateType, String docTemplateType, String customSchemaXml, SPFeatureDefinition listInstanceFeatureDefintion, QuickLaunchOptions quickLaunchOptions)
   at Microsoft.SharePoint.SPListCollection.Add_Client(SPListCreationInformation parameters)
   at Microsoft.SharePoint.ServerStub.SPListCollectionServerStub.InvokeMethod(Object target, String methodName, XmlNodeList xmlargs, ProxyContext proxyContext, Boolean& isVoid)
   at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, XmlNodeList args, ProxyContext proxyContext, Boolean& isVoid)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.InvokeMethod(Object obj, String methodName, XmlNodeList xmlargs, Boolean& isVoid)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPath(XmlElement xe)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPathId(String objectPathId)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessInstantiateObjectPath(XmlElement xe)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessOne(XmlElement xe)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessStatements(XmlNode xe)
   at Microsoft.SharePoint.Client.ClientMethodsProcessor.Process()
  StackTrace:
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 54
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 36
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance list, TokenParser parser, PnPMonitoredScope scope) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs:line 742
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs:line 85
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 181
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1031
       at Provisioning.Framework.Program.ApplyProvisioningTemplate(ConsoleColor defaultForeground, String webUrl, String userName, SecureString pwd) in ...\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 128
       at Provisioning.Framework.Program.Main(String[] args) in ...\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 36
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs:line 85
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 181
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in ...\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1031
       at Provisioning.Framework.Program.ApplyProvisioningTemplate(ConsoleColor defaultForeground, String webUrl, String userName, SecureString pwd) in ...\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 128
       at Provisioning.Framework.Program.Main(String[] args) in ...\PnP\Samples\Provisioning.Framework.Console\Provisioning.Framework.Console\Program.cs:line 36
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by PaoloPia** [comment]
Hi Carl,
thanks for your feedback. I'm wondering if it happens on-prem or in SharePoint Online, or in both scenarios. Moreover, is it still an open issue, even after some monthly releases of the engine? Thanks.

**Comment by erwinvanhunen** [comment]
No reply since Feb 21, I will close this issue, assuming it has been solved.
