### ISSUE TITLE
GetProvisioningTemplate ComposedLooks access denied error

### ISSUE THREAD

**Issue by biste5** [OfficeDev/PnP-Sites-Core#219]
Hi PnP team,

I'm trying to extract the template, of an existing sub site, currently in o365-D, and getting an exception with ComposedLooks Handler.

Some details about the error:

**Output**

```
01/10 - Regional Settings
02/10 - Supported UI Languages
03/10 - Fields
04/10 - Content Types
05/10 - List instances
06/10 - Custom Actions
07/10 - Features
08/10 - Composed Looks
ERROR: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 54
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs: line 36
   at Microsoft.SharePoint.Client.BrandingExtensions.GetComposedLook(Web web, String composedLookName) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\BrandingExtensions.cs:line 765   
   at Microsoft.SharePoint.Client.BrandingExtensions.GetCurrentComposedLook(Web web) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\BrandingExtensions.cs:line 718
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.DetectComposedLook(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, SharePointConnector spConnector, SharePointConnector spConnectorRoot) 
    in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectComposedLook.cs: line 231
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectComposedLook.cs:line 217
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 100
   at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo) in D:\GitHub\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1058
```

This as mentioned on 365-Dedicated tenant, with v15 assemblies referenced. I'm running the latest (self) build from dev branch. If I build a version of PnP with `ObjectComposedLook` commented out (I don't need to extract that piece in fact), template extraction is able to complete successfully.
I am a Site Collection Administrator.

Massimo

**Comment by PaoloPia** [comment]
Hi Massimo,
Thanks for your feedback. Considering that we heavily updated and refactored the Composed Look handling in the last two releases of the engine, I'm wondering if you're still experiencing the described issue. I will close this issue in the meantime, but if you are still having any issue let me know and I will be more than happy to re-open it. Thanks.

**Comment by biste5** [comment]
Hi Paolo,

i agree on this one. I was able to prevent that skipping the ComposedLooks handler. Now this can be done directly with settings/switches, so shouldn't be a problem.

Cheers
Massimo
