### ISSUE TITLE
Error when creating list template type 106 (Events)

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#227]
Error when creating list template type 106 (Events).

"Folders are not allowed for this template type" translated to English. Setting property EnableFolderCreation="false" solves the problem, but that shouldn't be neccessary.

Here's the XML for my list:

<pnp:ListInstance Title="Kalender" Description="" TemplateType="106" Url="Lists/Kalender" />

powershell.exe Information: 0 : 2015-12-03 10:13:58.3059        [List instances]        [7]     [Debug] Creating list Kalender failed: Mapper er ikke tillatt for denne listemalen. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance list, TokenParser parser, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)   1281ms  1c6afe23-5498-45f4-a2fb-ef312f246027
powershell.exe Information: 0 : 2015-12-03 10:13:58.3079        [List instances]        [7]     [Debug] Code execution scope ended
1284ms  1c6afe23-5498-45f4-a2fb-ef312f246027
powershell.exe Information: 0 : 2015-12-03 10:13:58.3089        [Provisioning]  [7]     [Debug] Code execution scope ended      2502ms       1c6afe23-5498-45f4-a2fb-ef312f246027

**Comment by VesaJuvonen** [comment]
Thanks Ole. Good catch as well. We'll get the exception handling included in the engine for Event library for this. Can't make to December release (tomorrow), but we'll get this included in the Jan release.

**Comment by olemp** [comment]
Good stuff, @VesaJuvonen

**Comment by VesaJuvonen** [comment]
I'll reopen this until it's fully fixed by the team, so that we can track this.

**Comment by olemp** [comment]
Ok @VesaJuvonen. I though you were adding issues to milestones.

**Comment by PaoloPia** [comment]
Hi, I've just fixed this issue with PR #400.

**Comment by oyvindam** [comment]
This is still as issue on 2.10.1612.0
