### ISSUE TITLE
Error when creating list template type 109 (PictureLibrary)

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#228]
Error when creating list template type 109 (PictureLibrary).

"Attachments are not allowed for this template type" translated to English. Setting property EnableAttachments="false" solves the problem, but that shouldn't be necessary.

Here's the XML for my list:

<pnp:ListInstance Title="Bildebibliotek" Description="" TemplateType="109" Url="Bildebibliotek" />

powershell.exe Information: 0 : 2015-12-03 10:25:15.3984        [List instances]        [7]     [Debug] Creating list Bildebibliotek failed: Vedlegg er ikke tillatt for dokumentbiblioteker og undersokelser. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance list, TokenParser parser, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)   1470ms  e8316878-76ec-40c5-a23f-284003f60bbe
powershell.exe Information: 0 : 2015-12-03 10:25:15.4013        [List instances]        [7]     [Debug] Code execution scope ended
1473ms  e8316878-76ec-40c5-a23f-284003f60bbe
powershell.exe Information: 0 : 2015-12-03 10:25:15.4018        [Provisioning]  [7]     [Debug] Code execution scope ended      2224ms       e8316878-76ec-40c5-a23f-284003f60bbe

**Comment by VesaJuvonen** [comment]
Thanks Ole. Good catch. We'll get the exception handling included in the engine for Picture library for this. Can't make to December release (tomorrow), but we'll get this included in the Jan release.

**Comment by olemp** [comment]
Good stuff, @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Reopen for tracking purposes. Will close when implemented for the Jan 2016 release.

**Comment by olemp** [comment]
Ok @VesaJuvonen. I though you were adding issues to milestones.

**Comment by erwinvanhunen** [comment]
It took a while, but the fix has finally been merged. Thank you for your patience.
