### ISSUE TITLE
Cannot convert object of type 'System.Int32' to type 'System.String[]' 

### ISSUE THREAD

**Issue by TVDKoni** [OfficeDev/PnP-Sites-Core#595]
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
[X ] Bug
[X ] Office 365 / SharePoint Online

Working with dev branch:
SHA-1: fc7289c3b81e83ffea741a497fa8188fd40ff692

Trying to upload a file with properties to the masterpage gallery:
```
<pnp:File Src="Control_TileNavSearchResults.js" Folder="{site}/_catalogs/masterpage/Display Templates/Trivadis" Overwrite="true">
<pnp:Properties>
<pnp:Property Key="Title" Value="Tile Navigation Result" />
<pnp:Property Key="ContentTypeId" Value="0x0101002039C03B61C64EC4A04F5361F385106601" />
<pnp:Property Key="MasterPageDescription" Value="Displays the Search Results control." />
<pnp:Property Key="UIVersion" Value="15" />
<pnp:Property Key="TemplateHidden" Value="0" />
<pnp:Property Key="TargetControlType" Value=";#SearchResults;#" />
<pnp:Property Key="DisplayTemplateLevel" Value="Base" />
</pnp:Properties>
</pnp:File>

```
Getting following error in property UIVersion:
System.InvalidOperationException: Cannot convert object of type 'System.Int32' to type 'System.String[]'
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at OfficeDevPnP.Core.Utilities.JsonUtility.Deserialize[T](String json) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Utilities\JsonUtility.cs:line 45
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFiles.SetFileProperties(File file, IDictionary`2 properties, Boolean checkoutIfRequired) in C:\Data\Source\github.com\TrivadisCloud\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectFiles.cs:line 259

**Comment by TVDKoni** [comment]
Fixed by using proper JSON formatting:
<pnp:Property Key="UIVersion" Value="[&quot;15&quot;]" />
<pnp:Property Key="TargetControlType" Value="[&quot;;#SearchResults;#&quot;]" />

Is this the suggested way?

**Comment by PaoloPia** [comment]
Hi,
It depends on the type of field. If it is a MultiChoice LookupMulti, or TaxonomyField of items/values we serialize it using Json.

**Comment by TVDKoni** [comment]
Ok. So I expect using JSON input will then be the right way :-)
