### ISSUE TITLE
Template provisioning works but throws sometimes « vti_mastercssfilecache » does not exist.

### ISSUE THREAD

**Issue by werocool** [OfficeDev/PnP-Sites-Core#62]
If you provision a new site collection and then run the following template, you will get an issue « vti_mastercssfilecache » does not exist. This is an on and off issue.

![image](https://cloud.githubusercontent.com/assets/4926713/9771691/b9dc41da-5705-11e5-8a8d-ec79406660c5.png)

Here's a the full stack trace:
Microsoft.SharePoint.Client.ServerException was unhandled
  HResult=-2146233088
  Message=Le champ ou la propriété « vti_mastercssfilecache » n’existe pas.
  ServerErrorCode=-1
  ServerErrorTraceCorrelationId=445a2c9d-50cc-2000-09f4-9f469bd16f9e
  ServerErrorTypeName=Microsoft.SharePoint.Client.InvalidClientQueryException
  ServerStackTrace=""
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 54
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 36
       at Microsoft.SharePoint.Client.WebExtensions.PropertyBagContainsKey(Web web, String key) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 771
       at Microsoft.SharePoint.Client.WebExtensions.GetIndexedPropertyBagKeys(Web web) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 807
       at Microsoft.SharePoint.Client.WebExtensions.AddIndexedPropertyBagKey(Web web, String key) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 828
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPersistTemplateInfo.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectPersistTemplateInfo.cs:line 26
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 177
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in C:\Git\Repos\PnP-Sites-Core\Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1037
       at CDP.SharePoint.Provisioning.Program.Main(String[] args) in C:\DEVLC\CDP.SharePoint.RAC\Dev_RacOnline\CDP.SharePoint.RAC\CDP.SharePoint.Provisioning\Program.cs:line 83
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by anderaus** [comment]
I'm experiencing the same issue on OfficeDevPnP.Core version 1.6.915.0.

**Comment by erwinvanhunen** [comment]
We are aware of the issue, and what is causing it. We contacted Microsoft about this (as it's not related to our code) but we also came up with a solution that we will implement very soon in the engine.

**Comment by sbelal** [comment]
What is the temporary workaround for this issue.  Is it deleting the "vti_mastercssfilecache" property?

**Comment by erwinvanhunen** [comment]
The vti_mastercssfilecache property is temporarily set by the server the moment you apply a composed look/theme. It removes that value but CSOM still caches it. 

If you use the latest build (or at least one later than the September release), we have fixed the issue in the core library. It has to do with the way the server removes the property bag value while CSOM still retains a cached reference to a value that is already removed from the property bag. Our Core library property bag methods are aware of this now and handle the propertybag calls a bit differently, skipping the cached values of CSOM.

**Comment by erwinvanhunen** [comment]
Closing the issue. If you feel that this issue still occurs using the latest builds, please do no hesitate to open it again.
