### ISSUE TITLE
Provisioning Engine: Referencing a Taxonomy Field in a Content Type results in an error

### ISSUE THREAD

**Issue by paulpascha** [OfficeDev/PnP-Sites-Core#72]
I have created an XML file based on Office PnP Provisioning Schema. In this XML file I've added XML that defines a Taxonomy Field and there's also XML that binds this field to one of my custom Content Type which is also defined in the template XML.

Applying the template to one of my sites results in the following error:

"The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

Stacktrace:

   at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
   at Microsoft.SharePoint.Client.Field.get_Id()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectContentType.UpdateContentType(Web web, ContentType existingContentType, ContentType templateContentType, TokenParser parser, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectContentType.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at ProvisioningConsole.Program.Main(String[] args) in D:\Source\PnP Provisioning Reference Implementation\ProvisioningConsole\Program.cs:line 45
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by jansenbe** [comment]
Paul's fix is implemented

**Comment by olemp** [comment]
@jansenbe Is PowerShell using the updated version of the Core module?
